spring:
  profiles:
    active: db
  web:
    resources:
      static-locations: classpath:/static/, file:images/

server:
  port: 9191
  servlet:
    context-path: /home

file:
  upload-dir: images

cloudinary:
   cloud-name: drzqytgdt
   api-key: 968449147357678
   api-secret: toZUNGbC3jF44TLI3RhyQiFG8gI